[package]
name = "rc-configurator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
users = "0.11.0"
clap = { version = "4.0.29", features = ["derive"] }
pancurses = "0.17.0"
